### ISSUE TITLE
About Discord API- Aryan

### ISSUE THREAD

**Issue by Ravanger101** [TurnipGuy30/TurnipGuy30#3]
Hello Turnip, 
(I am sorry I shouldn't post this here) Recently I have been working on Discord API in JS. The day after I tested it, I got mail from Discord: Your Account has been reported with SUSPICIOUS Activity, Your account will be Terminated. I lost all my Friends, Stuff and Servers. If you could help- Can you give me Invite to Xpavilion Server(Friends one).
Once Again I am so Sorry for posting it here.
Regards,
Aryan

**Comment by TurnipGuy30** [comment]
I'd be happy to help you, but please refrain from creating issues on my profile repository; my email address on my website, so please contact me there.

Looking forward to hearing from you.

**Comment by TurnipGuy30** [comment]
@Ravanger101 Edited my last message; my email is on my profile.
